### ISSUE TITLE
Build failure on RHEL 7 using python 3.6.8

### ISSUE THREAD

**Issue by rogin** [aivarsk/tuxedo-python#5]
First off, thank you for creating this project as I hope it'll make my Tuxedo integration a bit easier. Having said that, I get build errors with pretty much every combination I've tried. To focus on RHEL 7 using Python 3.6.8, I ran _pip install pybind11_ then attempted _pip install tuxedo_ which fails with the attached output. I have TUXDIR set and python dev headers installed. As the contents of the TUXDIR were populated on that machine before my time, how do you typically populate that folder, by pulling the latest [Oracle Tuxedo 22c (22.1.0.0.0) (Including Tuxedo, SALT and Jolt)](https://www.oracle.com/middleware/technologies/tuxedo-downloads.html)?
[install_out.txt](https://github.com/aivarsk/tuxedo-python/files/10263649/install_out.txt)

**Comment by aivarsk** [comment]
I have not tried Oracle Tuxedo 22c yet, that's in my TODO for mid-January.

Commands to install Tuxedo 12c using the answer file can be found at https://github.com/aivarsk/oracle-tuxedo-for-developers-code/tree/main/docker and sometimes I run `runInstaller.sh -console` from `Disk1/install/` to install files manually.

For the issue you have I have uploaded a new version of the package that builds with C++11 (the maximum that your compiler supports), I have compilers that support C++17 or at least C++14. 
It looks like a second error might be because you might have only Tuxedo 11.1 client headers. I'm not 100% sure because I have not tried it myself. If you are installing Tuxedo yourself, choose a "Full install" instead of "Client install".

**Comment by rogin** [comment]
Great news in that I was able to install 12c according to your docker example and v1.0.9 then installed successfully via pip3. Thank you for the quick resolution.
