### ISSUE TITLE
Client configuration to access remote server

### ISSUE THREAD

**Issue by rogin** [aivarsk/tuxedo-python#6]
In following README.rst and py3/client.py, I'm unable to create a client that accesses a remote server and would appreciate any assistance. The attached minimal client fails until a server is created locally and run via tmboot. After starting the local server via tmboot, ULOG shows failure to find the endpoint, of which I believe it's still looking at the local server.

[sample.py.txt](https://github.com/aivarsk/tuxedo-python/files/10355298/sample.py.txt)
[source.env.txt](https://github.com/aivarsk/tuxedo-python/files/10355376/source.env.txt)
[ULOG-test-env.txt](https://github.com/aivarsk/tuxedo-python/files/10355377/ULOG-test-env.txt)

**Comment by aivarsk** [comment]
To connect to a remote server you must import `tuxedowsc` module instead of `tuxedo` . Here is an example for that
https://github.com/PacktPublishing/Modernizing-Oracle-Tuxedo-Applications-with-Python/blob/main/Chapter10/wsclient.py

Book has a chapter about connecting to a local/remote server but I should add something to README as well.

**Comment by rogin** [comment]
Great, that simple replacement enabled my sample client to connect. I'll have to pick up your book to better understand the library. Thank you.
